// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxCpFjiwPIs47AN111lZQ0HizsBoNEnc',
    appId: '1:70417636499:web:66b053aa86df7f893f8166',
    messagingSenderId: '70417636499',
    projectId: 'flutter-chat-application-12f98',
    authDomain: 'flutter-chat-application-12f98.firebaseapp.com',
    storageBucket: 'flutter-chat-application-12f98.appspot.com',
    measurementId: 'G-RMWK9EZSQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCih_r5LjMYUtl9sjORtWP5tzvu71T_M',
    appId: '1:70417636499:android:65f85d93b931bff63f8166',
    messagingSenderId: '70417636499',
    projectId: 'flutter-chat-application-12f98',
    storageBucket: 'flutter-chat-application-12f98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlQTtaEaq2SJJFcN5M0IKmFAcG_g_pHeg',
    appId: '1:70417636499:ios:02edd16531b4b1373f8166',
    messagingSenderId: '70417636499',
    projectId: 'flutter-chat-application-12f98',
    storageBucket: 'flutter-chat-application-12f98.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlQTtaEaq2SJJFcN5M0IKmFAcG_g_pHeg',
    appId: '1:70417636499:ios:f4a622da852f1a333f8166',
    messagingSenderId: '70417636499',
    projectId: 'flutter-chat-application-12f98',
    storageBucket: 'flutter-chat-application-12f98.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
